### ISSUE TITLE
[Enhancement] Procedural repairing

### ISSUE THREAD

**Issue by Uboaaaaa** [dev-stan/AnvilRepair#2]
Here's an idea:

Repairing a damaged anvil turns it into a chipped anvil.

Repairing a chipped anvil turn it into an (undamaged) anvil.

**Comment by dev-stan** [comment]
I've implemented this feature in the latest [update](https://www.spigotmc.org/resources/anvil-repair.92462/), thanks for the suggestion!
[damaged_anvil -> chipped_anvil -> anvil](https://giphy.com/gifs/d7aaaGF2j0u85YT9tR)
