### ISSUE TITLE
[Enhancement] Configurable material

### ISSUE THREAD

**Issue by Uboaaaaa** [dev-stan/AnvilRepair#3]
Hi! I think it would be nice if people can configure which material they can use to perform repairing.
Personally I would love to repair anvils with iron blocks, but I'm not very sure about doing so with other damaged anvils... Some might also want this to be easier, therefore prefers to do it with iron ingots.

**Comment by dev-stan** [comment]
That's a great suggestion, I've implemented custom repair items in the [1.2.2 patch](https://www.spigotmc.org/resources/anvil-repair.92462/)
