### ISSUE TITLE
Isn't consuming blocks

### ISSUE THREAD

**Issue by Yollan-E** [dev-stan/AnvilRepair#7]
In 1.18.1 iron blocks are fixing the anvils but players dont lose the iron blocks for some reason

**Comment by dev-stan** [comment]
The plugin hasn't yet been updated to the newest version, I'll look into this issue as soon as I can though

**Comment by Yollan-E** [comment]
Okay thank you

**Comment by dev-stan** [comment]
Hey, are you sure you weren't an operator while the items weren't getting removed? The plugin has a no-price permission which you might have automatically inherited as an operator `no-price: "arepair.no-price"`.

I just tested the plugin's newest version on a 1.18 server while only having the `are
pair.use` permission and the plugin worked as it should. Please try giving yourself only this one permission and let me know if that fixes your issue. Here's the build I used to test the plugin: [version-i-tested-with.jar](https://www.spigotmc.org/resources/anvil-repair.92462/download?version=412143)

**Comment by Yollan-E** [comment]
Okay that fixed it! Thank you!
